// ─── Voice Ordering Analytics Mock Data ───
// Simulates 45 days of AI voice ordering data (Jan 8 – Feb 21, 2026)

export interface VoiceOrder {
  id: string;
  date: string; // ISO
  session_duration_seconds: number;
  order_completed: boolean;
  delivery_type: "delivery" | "pickup";
  items: { name: string; category: "veg_pizza" | "nonveg_pizza" | "sides" | "desserts" | "beverages"; quantity: number }[];
  subtotal: number;
  total: number;
  offer_applied: string | null;
  discount: number;
  language: "english" | "hindi" | "hinglish";
  city: string;
}

export const voiceOrders: VoiceOrder[] = [
  // ── January 2026 ─────────────────────────
  { id: "VO-001", date: "2026-01-08T11:30:00Z", session_duration_seconds: 85, order_completed: true, delivery_type: "delivery", items: [{ name: "Margherita", category: "veg_pizza", quantity: 1 }, { name: "Garlic Breadsticks", category: "sides", quantity: 1 }], subtotal: 348, total: 395, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-002", date: "2026-01-08T13:15:00Z", session_duration_seconds: 120, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Dominator", category: "nonveg_pizza", quantity: 1 }, { name: "Coca-Cola", category: "beverages", quantity: 2 }], subtotal: 997, total: 1077, offer_applied: null, discount: 0, language: "hinglish", city: "Mumbai" },
  { id: "VO-003", date: "2026-01-09T19:00:00Z", session_duration_seconds: 65, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "hindi", city: "Delhi" },
  { id: "VO-004", date: "2026-01-10T12:45:00Z", session_duration_seconds: 95, order_completed: true, delivery_type: "pickup", items: [{ name: "Peppy Paneer", category: "veg_pizza", quantity: 2 }, { name: "Choco Lava Cake", category: "desserts", quantity: 2 }], subtotal: 816, total: 857, offer_applied: "2 Regular @ ₹99", discount: 102, language: "english", city: "Bengaluru" },
  { id: "VO-005", date: "2026-01-11T20:30:00Z", session_duration_seconds: 110, order_completed: true, delivery_type: "delivery", items: [{ name: "Non-Veg Supreme", category: "nonveg_pizza", quantity: 1 }, { name: "Chicken Wings", category: "sides", quantity: 1 }, { name: "Sprite", category: "beverages", quantity: 1 }], subtotal: 727, total: 793, offer_applied: null, discount: 0, language: "hinglish", city: "Hyderabad" },
  { id: "VO-006", date: "2026-01-13T13:00:00Z", session_duration_seconds: 72, order_completed: true, delivery_type: "pickup", items: [{ name: "Farmhouse", category: "veg_pizza", quantity: 1 }], subtotal: 349, total: 367, offer_applied: null, discount: 0, language: "english", city: "Pune" },
  { id: "VO-007", date: "2026-01-14T18:45:00Z", session_duration_seconds: 140, order_completed: true, delivery_type: "delivery", items: [{ name: "Pepper Barbecue Chicken", category: "nonveg_pizza", quantity: 1 }, { name: "Cheese & Corn", category: "veg_pizza", quantity: 1 }, { name: "Stuffed Garlic Bread", category: "sides", quantity: 1 }, { name: "Coca-Cola", category: "beverages", quantity: 2 }], subtotal: 1076, total: 1130, offer_applied: "Free Delivery 399+", discount: 30, language: "hindi", city: "Delhi" },
  { id: "VO-008", date: "2026-01-15T12:00:00Z", session_duration_seconds: 55, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "english", city: "Chennai" },
  { id: "VO-009", date: "2026-01-16T19:30:00Z", session_duration_seconds: 90, order_completed: true, delivery_type: "delivery", items: [{ name: "Double Cheese Margherita", category: "veg_pizza", quantity: 1 }, { name: "Butterscotch Mousse Cake", category: "desserts", quantity: 1 }], subtotal: 508, total: 564, offer_applied: null, discount: 0, language: "hinglish", city: "Mumbai" },
  { id: "VO-010", date: "2026-01-17T13:30:00Z", session_duration_seconds: 78, order_completed: true, delivery_type: "pickup", items: [{ name: "Veg Extravaganza", category: "veg_pizza", quantity: 1 }, { name: "Peri Peri Garlic Bread", category: "sides", quantity: 1 }], subtotal: 498, total: 523, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-011", date: "2026-01-19T20:00:00Z", session_duration_seconds: 130, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Golden Delight", category: "nonveg_pizza", quantity: 2 }, { name: "Garlic Breadsticks", category: "sides", quantity: 1 }, { name: "Thums Up", category: "beverages", quantity: 2 }], subtotal: 1005, total: 1055, offer_applied: "Free Delivery 399+", discount: 30, language: "hindi", city: "Lucknow" },
  { id: "VO-012", date: "2026-01-20T12:15:00Z", session_duration_seconds: 68, order_completed: true, delivery_type: "pickup", items: [{ name: "Margherita", category: "veg_pizza", quantity: 2 }], subtotal: 398, total: 418, offer_applied: "2 Regular @ ₹99", discount: 100, language: "english", city: "Pune" },
  { id: "VO-013", date: "2026-01-21T18:00:00Z", session_duration_seconds: 45, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "hinglish", city: "Mumbai" },
  { id: "VO-014", date: "2026-01-22T19:45:00Z", session_duration_seconds: 105, order_completed: true, delivery_type: "delivery", items: [{ name: "Indi Chicken Tikka", category: "nonveg_pizza", quantity: 1 }, { name: "Paneer Makhani", category: "veg_pizza", quantity: 1 }, { name: "Red Velvet Lava Cake", category: "desserts", quantity: 2 }], subtotal: 916, total: 992, offer_applied: null, discount: 0, language: "hindi", city: "Delhi" },
  { id: "VO-015", date: "2026-01-23T13:00:00Z", session_duration_seconds: 82, order_completed: true, delivery_type: "pickup", items: [{ name: "Mexican Green Wave", category: "veg_pizza", quantity: 1 }, { name: "Fanta", category: "beverages", quantity: 1 }], subtotal: 428, total: 449, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-016", date: "2026-01-25T20:30:00Z", session_duration_seconds: 98, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Fiesta", category: "nonveg_pizza", quantity: 1 }, { name: "Stuffed Garlic Bread", category: "sides", quantity: 1 }], subtotal: 648, total: 711, offer_applied: null, discount: 0, language: "hinglish", city: "Hyderabad" },
  { id: "VO-017", date: "2026-01-27T12:30:00Z", session_duration_seconds: 60, order_completed: true, delivery_type: "pickup", items: [{ name: "Fresh Veggie", category: "veg_pizza", quantity: 1 }], subtotal: 199, total: 209, offer_applied: null, discount: 0, language: "hindi", city: "Jaipur" },
  { id: "VO-018", date: "2026-01-28T19:00:00Z", session_duration_seconds: 115, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Pepperoni", category: "nonveg_pizza", quantity: 1 }, { name: "Veg Pasta", category: "sides", quantity: 1 }, { name: "Choco Lava Cake", category: "desserts", quantity: 1 }, { name: "Coca-Cola", category: "beverages", quantity: 1 }], subtotal: 786, total: 855, offer_applied: "Free Delivery 399+", discount: 30, language: "english", city: "Mumbai" },
  { id: "VO-019", date: "2026-01-29T13:45:00Z", session_duration_seconds: 42, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "hindi", city: "Delhi" },
  { id: "VO-020", date: "2026-01-30T20:15:00Z", session_duration_seconds: 88, order_completed: true, delivery_type: "delivery", items: [{ name: "Indi Tandoori Paneer", category: "veg_pizza", quantity: 1 }, { name: "Potato Cheese Shots", category: "sides", quantity: 1 }], subtotal: 448, total: 501, offer_applied: null, discount: 0, language: "hinglish", city: "Bengaluru" },

  // ── February 2026 ─────────────────────────
  { id: "VO-021", date: "2026-02-01T12:00:00Z", session_duration_seconds: 75, order_completed: true, delivery_type: "pickup", items: [{ name: "Margherita", category: "veg_pizza", quantity: 1 }, { name: "Garlic Breadsticks", category: "sides", quantity: 1 }], subtotal: 348, total: 365, offer_applied: null, discount: 0, language: "english", city: "Chennai" },
  { id: "VO-022", date: "2026-02-02T19:30:00Z", session_duration_seconds: 125, order_completed: true, delivery_type: "delivery", items: [{ name: "Non-Veg Supreme", category: "nonveg_pizza", quantity: 1 }, { name: "Chicken Wings", category: "sides", quantity: 1 }, { name: "Sprite", category: "beverages", quantity: 2 }], subtotal: 885, total: 959, offer_applied: "Free Delivery 399+", discount: 30, language: "hindi", city: "Delhi" },
  { id: "VO-023", date: "2026-02-03T13:15:00Z", session_duration_seconds: 70, order_completed: true, delivery_type: "pickup", items: [{ name: "Peppy Paneer", category: "veg_pizza", quantity: 1 }], subtotal: 249, total: 261, offer_applied: null, discount: 0, language: "english", city: "Pune" },
  { id: "VO-024", date: "2026-02-04T20:00:00Z", session_duration_seconds: 135, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Dominator", category: "nonveg_pizza", quantity: 1 }, { name: "Double Cheese Margherita", category: "veg_pizza", quantity: 1 }, { name: "Choco Lava Cake", category: "desserts", quantity: 2 }], subtotal: 1267, total: 1361, offer_applied: "Free Delivery 399+", discount: 30, language: "hinglish", city: "Mumbai" },
  { id: "VO-025", date: "2026-02-05T12:30:00Z", session_duration_seconds: 38, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-026", date: "2026-02-06T18:45:00Z", session_duration_seconds: 92, order_completed: true, delivery_type: "delivery", items: [{ name: "Farmhouse", category: "veg_pizza", quantity: 1 }, { name: "Peri Peri Garlic Bread", category: "sides", quantity: 1 }, { name: "Mirinda", category: "beverages", quantity: 1 }], subtotal: 577, total: 636, offer_applied: null, discount: 0, language: "hindi", city: "Lucknow" },
  { id: "VO-027", date: "2026-02-07T13:00:00Z", session_duration_seconds: 80, order_completed: true, delivery_type: "pickup", items: [{ name: "Cheese & Corn", category: "veg_pizza", quantity: 2 }], subtotal: 498, total: 523, offer_applied: "2 Regular @ ₹99", discount: 100, language: "english", city: "Bengaluru" },
  { id: "VO-028", date: "2026-02-08T19:15:00Z", session_duration_seconds: 108, order_completed: true, delivery_type: "delivery", items: [{ name: "Pepper Barbecue Chicken", category: "nonveg_pizza", quantity: 1 }, { name: "Veg Extravaganza", category: "veg_pizza", quantity: 1 }, { name: "Coca-Cola", category: "beverages", quantity: 2 }], subtotal: 897, total: 972, offer_applied: "Free Delivery 399+", discount: 30, language: "hinglish", city: "Hyderabad" },
  { id: "VO-029", date: "2026-02-09T12:45:00Z", session_duration_seconds: 58, order_completed: true, delivery_type: "pickup", items: [{ name: "Margherita", category: "veg_pizza", quantity: 1 }], subtotal: 199, total: 209, offer_applied: null, discount: 0, language: "hindi", city: "Jaipur" },
  { id: "VO-030", date: "2026-02-10T20:30:00Z", session_duration_seconds: 50, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "english", city: "Chennai" },
  { id: "VO-031", date: "2026-02-11T13:30:00Z", session_duration_seconds: 95, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Golden Delight", category: "nonveg_pizza", quantity: 1 }, { name: "Stuffed Garlic Bread", category: "sides", quantity: 1 }, { name: "Butterscotch Mousse Cake", category: "desserts", quantity: 1 }], subtotal: 757, total: 825, offer_applied: null, discount: 0, language: "hinglish", city: "Mumbai" },
  { id: "VO-032", date: "2026-02-12T19:00:00Z", session_duration_seconds: 85, order_completed: true, delivery_type: "pickup", items: [{ name: "Paneer Makhani", category: "veg_pizza", quantity: 1 }, { name: "Thums Up", category: "beverages", quantity: 1 }], subtotal: 428, total: 449, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-033", date: "2026-02-13T12:15:00Z", session_duration_seconds: 100, order_completed: true, delivery_type: "delivery", items: [{ name: "Indi Chicken Tikka", category: "nonveg_pizza", quantity: 1 }, { name: "Garlic Breadsticks", category: "sides", quantity: 1 }], subtotal: 548, total: 606, offer_applied: null, discount: 0, language: "hindi", city: "Delhi" },
  { id: "VO-034", date: "2026-02-14T20:00:00Z", session_duration_seconds: 145, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Pepperoni", category: "nonveg_pizza", quantity: 1 }, { name: "Peppy Paneer", category: "veg_pizza", quantity: 1 }, { name: "Red Velvet Lava Cake", category: "desserts", quantity: 2 }, { name: "Coca-Cola", category: "beverages", quantity: 2 }], subtotal: 1184, total: 1274, offer_applied: "Free Delivery 399+", discount: 30, language: "english", city: "Pune" },
  { id: "VO-035", date: "2026-02-15T13:00:00Z", session_duration_seconds: 72, order_completed: true, delivery_type: "pickup", items: [{ name: "Mexican Green Wave", category: "veg_pizza", quantity: 1 }], subtotal: 349, total: 367, offer_applied: null, discount: 0, language: "hinglish", city: "Hyderabad" },
  { id: "VO-036", date: "2026-02-16T19:30:00Z", session_duration_seconds: 88, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Fiesta", category: "nonveg_pizza", quantity: 1 }, { name: "Veg Pasta", category: "sides", quantity: 1 }], subtotal: 598, total: 658, offer_applied: null, discount: 0, language: "hindi", city: "Delhi" },
  { id: "VO-037", date: "2026-02-17T12:30:00Z", session_duration_seconds: 62, order_completed: true, delivery_type: "pickup", items: [{ name: "Fresh Veggie", category: "veg_pizza", quantity: 1 }, { name: "Fanta", category: "beverages", quantity: 1 }], subtotal: 278, total: 292, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-038", date: "2026-02-18T20:15:00Z", session_duration_seconds: 115, order_completed: true, delivery_type: "delivery", items: [{ name: "Non-Veg Supreme", category: "nonveg_pizza", quantity: 1 }, { name: "Double Cheese Margherita", category: "veg_pizza", quantity: 1 }, { name: "Chicken Wings", category: "sides", quantity: 1 }], subtotal: 1046, total: 1128, offer_applied: "Free Delivery 399+", discount: 30, language: "hinglish", city: "Mumbai" },
  { id: "VO-039", date: "2026-02-19T13:15:00Z", session_duration_seconds: 40, order_completed: false, delivery_type: "delivery", items: [], subtotal: 0, total: 0, offer_applied: null, discount: 0, language: "hindi", city: "Lucknow" },
  { id: "VO-040", date: "2026-02-19T19:45:00Z", session_duration_seconds: 98, order_completed: true, delivery_type: "delivery", items: [{ name: "Farmhouse", category: "veg_pizza", quantity: 1 }, { name: "Choco Lava Cake", category: "desserts", quantity: 2 }], subtotal: 567, total: 626, offer_applied: null, discount: 0, language: "english", city: "Chennai" },
  { id: "VO-041", date: "2026-02-20T12:00:00Z", session_duration_seconds: 82, order_completed: true, delivery_type: "pickup", items: [{ name: "Veg Extravaganza", category: "veg_pizza", quantity: 1 }, { name: "Potato Cheese Shots", category: "sides", quantity: 1 }], subtotal: 448, total: 470, offer_applied: null, discount: 0, language: "english", city: "Bengaluru" },
  { id: "VO-042", date: "2026-02-20T19:30:00Z", session_duration_seconds: 128, order_completed: true, delivery_type: "delivery", items: [{ name: "Chicken Dominator", category: "nonveg_pizza", quantity: 1 }, { name: "Indi Tandoori Paneer", category: "veg_pizza", quantity: 1 }, { name: "Stuffed Garlic Bread", category: "sides", quantity: 1 }, { name: "Sprite", category: "beverages", quantity: 2 }], subtotal: 1225, total: 1317, offer_applied: "Free Delivery 399+", discount: 30, language: "hindi", city: "Delhi" },
  { id: "VO-043", date: "2026-02-21T11:30:00Z", session_duration_seconds: 70, order_completed: true, delivery_type: "pickup", items: [{ name: "Margherita", category: "veg_pizza", quantity: 2 }], subtotal: 398, total: 418, offer_applied: "2 Regular @ ₹99", discount: 100, language: "english", city: "Pune" },
  { id: "VO-044", date: "2026-02-21T13:45:00Z", session_duration_seconds: 105, order_completed: true, delivery_type: "delivery", items: [{ name: "Pepper Barbecue Chicken", category: "nonveg_pizza", quantity: 1 }, { name: "Peri Peri Garlic Bread", category: "sides", quantity: 1 }, { name: "Butterscotch Mousse Cake", category: "desserts", quantity: 1 }], subtotal: 758, total: 826, offer_applied: null, discount: 0, language: "hinglish", city: "Hyderabad" },
  { id: "VO-045", date: "2026-02-21T19:00:00Z", session_duration_seconds: 92, order_completed: true, delivery_type: "delivery", items: [{ name: "Cheese & Corn", category: "veg_pizza", quantity: 1 }, { name: "Coca-Cola", category: "beverages", quantity: 1 }], subtotal: 328, total: 375, offer_applied: null, discount: 0, language: "hindi", city: "Mumbai" },
];
